configs, kernel, udev, wallpapers, etc

diff --git a/setup-arch b/setup-arch
--- a/setup-arch
+++ b/setup-arch
@@ -3,8 +3,8 @@
 # Created by argbash-init v2.11.0
 # ARG_OPTIONAL_SINGLE([root-dir],[r],[Path to the root directory])
 # ARG_OPTIONAL_BOOLEAN([dry-run],[d],[Perform a trial run with no changes made])
-# ARG_POSITIONAL_SINGLE([command],[The command to execute])
-# ARG_TYPE_GROUP_SET([ops],[op],[command],[install])
+# ARG_POSITIONAL_SINGLE([command],[The command to execute. Possible commands:\n ---------------------\n- system - setup base system (time and date sync, yay setup, etc.\n- install - install pacmand and AUR packages\n- config - setup config files\n ---------------------\n])
+# ARG_TYPE_GROUP_SET([ops],[op],[command],[install, config, system])
 # ARG_DEFAULTS_POS([])
 # ARG_HELP([Arch "setup everything" script.],[Arch Linux setup script for packages, configs, udev rules, ketnel flags, etc.])
 # ARGBASH_GO()
@@ -13,9 +13,7 @@
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.dev for more info
 
-
-die()
-{
+die() {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	echo "$1" >&2
@@ -24,19 +22,15 @@ die()
 
 # validators
 
-ops()
-{
-	local _allowed=("install") _seeking="$1"
-	for element in "${_allowed[@]}"
-	do
+ops() {
+	local _allowed=("install" "config" "system") _seeking="$1"
+	for element in "${_allowed[@]}"; do
 		test "$element" = "$_seeking" && echo "$element" && return 0
 	done
-	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'install'" 4
+	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'install', 'config' and 'system'" 4
 }
 
-
-begins_with_short_option()
-{
+begins_with_short_option() {
 	local first_option all_short_options='rdh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
@@ -49,85 +43,80 @@ _arg_command=
 _arg_root_dir=
 _arg_dry_run="off"
 
-
-print_help()
-{
+print_help() {
 	printf '%s\n' "Arch \"setup everything\" script."
 	printf 'Usage: %s [-r|--root-dir <arg>] [-d|--(no-)dry-run] [-h|--help] <command>\n' "$0"
-	printf '\t%s\n' "<command>: The command to execute. Can be one of: 'install'"
+	printf '\t%s\n' "<command>: The command to execute. Possible commands:
+		 ---------------------
+		- system - setup base system (time and date sync, yay setup, pacman extras, etc.
+		- install - install pacmand and AUR packages
+		- config - setup config files
+		 ---------------------
+		. Can be one of: 'install', 'config' and 'system'"
 	printf '\t%s\n' "-r, --root-dir: Path to the root directory (no default)"
 	printf '\t%s\n' "-d, --dry-run, --no-dry-run: Perform a trial run with no changes made (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 	printf '\n%s\n' "Arch Linux setup script for packages, configs, udev rules, ketnel flags, etc."
 }
 
-
-parse_commandline()
-{
+parse_commandline() {
 	_positionals_count=0
 	local _key
-	while test $# -gt 0
-	do
+	while test $# -gt 0; do
 		_key="$1"
 		case "$_key" in
-			-r|--root-dir)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_root_dir="$2"
-				shift
-				;;
-			--root-dir=*)
-				_arg_root_dir="${_key##--root-dir=}"
-				;;
-			-r*)
-				_arg_root_dir="${_key##-r}"
-				;;
-			-d|--no-dry-run|--dry-run)
-				_arg_dry_run="on"
-				test "${1:0:5}" = "--no-" && _arg_dry_run="off"
-				;;
-			-d*)
-				_arg_dry_run="on"
-				_next="${_key##-d}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					{ begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
-				;;
-			-h|--help)
-				print_help
-				exit 0
-				;;
-			-h*)
-				print_help
-				exit 0
-				;;
-			*)
-				_last_positional="$1"
-				_positionals+=("$_last_positional")
-				_positionals_count=$((_positionals_count + 1))
-				;;
+		-r | --root-dir)
+			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			_arg_root_dir="$2"
+			shift
+			;;
+		--root-dir=*)
+			_arg_root_dir="${_key##--root-dir=}"
+			;;
+		-r*)
+			_arg_root_dir="${_key##-r}"
+			;;
+		-d | --no-dry-run | --dry-run)
+			_arg_dry_run="on"
+			test "${1:0:5}" = "--no-" && _arg_dry_run="off"
+			;;
+		-d*)
+			_arg_dry_run="on"
+			_next="${_key##-d}"
+			if test -n "$_next" -a "$_next" != "$_key"; then
+				{ begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+			fi
+			;;
+		-h | --help)
+			print_help
+			exit 0
+			;;
+		-h*)
+			print_help
+			exit 0
+			;;
+		*)
+			_last_positional="$1"
+			_positionals+=("$_last_positional")
+			_positionals_count=$((_positionals_count + 1))
+			;;
 		esac
 		shift
 	done
 }
 
-
-handle_passed_args_count()
-{
+handle_passed_args_count() {
 	local _required_args_string="'command'"
 	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
 	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
-
-assign_positional_args()
-{
+assign_positional_args() {
 	local _positional_name _shift_for=$1
 	_positional_names="_arg_command "
 
 	shift "$_shift_for"
-	for _positional_name in ${_positional_names}
-	do
+	for _positional_name in ${_positional_names}; do
 		test $# -gt 0 || break
 		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
 		shift
@@ -142,28 +131,27 @@ assign_positional_args 1 "${_positionals[@]}"
 # Validation of values
 _arg_command="$(ops "$_arg_command" "command")" || exit 1
 
-
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
-
 
 # vvv  PLACE YOUR CODE HERE  vvv
 set -euo pipefail
 
-ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )" 
+ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
 if [[ -n "$_arg_root_dir" ]]; then
-    ROOT_DIR="$_arg_root_dir"
+	ROOT_DIR="$_arg_root_dir"
 fi
 
 source "${ROOT_DIR}/scripts/utils.sh"
 source "${ROOT_DIR}/scripts/pkg-install-utils.sh"
+source "${ROOT_DIR}/scripts/arch-utils.sh"
 
 handle_error() {
-    local exit_code=$?
-    local last_command=$BASH_COMMAND
-    local line_num=$LINENO
-    error "An error occurred during script execution.ERROR on line $line_num: Command '\"$last_command\"' failed."
-    exit $exit_code;
+	local exit_code=$?
+	local last_command=$BASH_COMMAND
+	local line_num=$LINENO
+	error "An error occurred during script execution.ERROR on line $line_num: Command '\"$last_command\"' failed."
+	exit $exit_code
 }
 
 trap 'handle_error' ERR
@@ -176,28 +164,75 @@ warn "Value of 'DRY_RUN': $DRY_RUN"
 warn "'dry-run' is $_arg_dry_run"
 warn "Value of 'command': $_arg_command"
 
-
 case "$_arg_command" in
-	install)
-		if read_yes_no "Update system before installing packages?"; then
-		    update_system
-		    success "System packages updated successfully."
-			success
-		else
-		    info "Skipping system update."
-		fi
-		install_packages_from_file "${ROOT_DIR}/pacman-pkgs.txt" "pacman"
+system)
+	info "Setting up system time and date sync..."
+	run sudo timedatectl set-ntp true
+	success "System time and date sync setup successfully."
+
+	run install_yay
+	run setup_kernel_modules
+	run setup_udev_rules
+	run setup_pacman_mirrorlist
+	;;
+install)
+	if read_yes_no "Update system before installing packages?"; then
+		update_system
+		success "System packages updated successfully."
 		success
-		success "Pacman packages installed successfully."
-		success
-		install_packages_from_file "${ROOT_DIR}/aur-pkgs.txt" "yay"
-		success
-		success "AUR packages installed successfully."
-		success
-		;;
-	*)
-		die "Unsupported command: $_arg_command"
-		;;
+	else
+		info "Skipping system update."
+	fi
+	install_packages_from_file "${ROOT_DIR}/pacman-pkgs.txt" "pacman"
+	success
+	success "Pacman packages installed successfully."
+	success
+	install_packages_from_file "${ROOT_DIR}/aur-pkgs.txt" "yay"
+	success
+	success "AUR packages installed successfully."
+	success
+
+	info "Installing Oh My Zsh..."
+	if [[ ! -d ~/.oh-my-zsh ]]; then
+		run sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+		success "Oh My Zsh installed successfully."
+	else
+		info "Oh My Zsh is already installed. Skipping installation."
+	fi
+
+	info "Installing Zsh Shift Select Mode plugin..."
+	if [[ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-shift-select ]]; then
+		run git clone https://github.com/jirutka/zsh-shift-select.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-shift-select
+		success "Zsh Shift Select Mode plugin installed successfully."
+	else
+		info "Zsh Shift Select Mode plugin is already installed. Skipping installation."
+	fi
+
+	info "Copying shell profile settings..."
+	run cp -rv $ROOT_DIR/shell/. ~/
+	success "Shell profile settings copied successfully."
+
+	info "Setting Zsh as the default shell..."
+	run chsh -s "$(which zsh)"
+	success "Zsh set as the default shell successfully."
+	;;
+config)
+	info "Copying dot config files..."
+	run cp -r -v $ROOT_DIR/.config/ ~/
+	success "Dot config files copied successfully."
+
+	info "Copying wallpapers..."
+	run sudo cp -r -v $ROOT_DIR/wallpapers/ /usr/share/
+	success "Wallpapers copied successfully."
+
+	info "Copying config files to /etc/ ..."
+	run sudo cp -r -v $ROOT_DIR/etc/ /
+	success "Config /etc files copied successfully."
+	;;
+*)
+	error "Unsupported command: $_arg_command"
+	exit 1
+	;;
 esac
 # ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
 
