refactor setup script - use single file for arg parsing and logic; add completions file

diff --git a/setup-arch b/setup-arch
--- a/setup-arch
+++ b/setup-arch
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
 # Created by argbash-init v2.11.0
-# ARG_OPTIONAL_SINGLE([root-dir],[r],[Path to the repository root directory])
+# ARG_OPTIONAL_SINGLE([root-dir],[r],[Path to the root directory])
 # ARG_OPTIONAL_BOOLEAN([dry-run],[d],[Perform a trial run with no changes made])
 # ARG_POSITIONAL_SINGLE([command],[The command to execute])
 # ARG_TYPE_GROUP_SET([ops],[op],[command],[install])
 # ARG_DEFAULTS_POS([])
-# ARG_HELP([Arch "setup everything" script.],[Arch Linux setup script for packages, configs, udev rules, ketnel flags, etc.])					>]) # ARGBASH_GO()
+# ARG_HELP([Arch "setup everything" script.],[Arch Linux setup script for packages, configs, udev rules, ketnel flags, etc.])
+# ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
@@ -54,7 +55,7 @@ print_help()
 	printf '%s\n' "Arch \"setup everything\" script."
 	printf 'Usage: %s [-r|--root-dir <arg>] [-d|--(no-)dry-run] [-h|--help] <command>\n' "$0"
 	printf '\t%s\n' "<command>: The command to execute. Can be one of: 'install'"
-	printf '\t%s\n' "-r, --root-dir: Path to the repository root directory (no default)"
+	printf '\t%s\n' "-r, --root-dir: Path to the root directory (no default)"
 	printf '\t%s\n' "-d, --dry-run, --no-dry-run: Perform a trial run with no changes made (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 	printf '\n%s\n' "Arch Linux setup script for packages, configs, udev rules, ketnel flags, etc."
@@ -143,3 +144,34 @@ _arg_command="$(ops "$_arg_command" "command")" || exit 1
 
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
+
+# vvv  PLACE YOUR CODE HERE  vvv
+ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )" 
+if [[ -n "$_arg_root_dir" ]]; then
+    ROOT_DIR="$_arg_root_dir"
+fi
+
+source "${ROOT_DIR}/scripts/utils.sh"
+
+handle_error() {
+    local exit_code=$?
+    local last_command=$BASH_COMMAND
+    local line_num=$LINENO
+    error "An error occurred during script execution.ERROR on line $line_num: Command '\"$last_command\"' failed."
+    exit $exit_code;
+}
+
+trap 'handle_error' ERR
+
+DRY_RUN=false
+[[ $_arg_dry_run == "on" ]] && DRY_RUN=true
+
+warn "Value of 'ROOT_DIR': $ROOT_DIR"
+warn "Value of 'DRY_RUN': $DRY_RUN"
+warn "'dry-run' is $_arg_dry_run"
+warn "Value of 'command': $_arg_command"
+# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
+
+# ] <-- needed because of Argbash
